### ISSUE TITLE
How to create viable_with_validation_and_random_test.json   

### ISSUE THREAD

**Issue by pankajbadatia** [golmschenk/crowdnetdata#1]
Can you please share the file 
I was reading your dataset.py file
It's not working. No other files generate  JSON files.

I have used your database.py and  unlabeled_data_processing.py  file  they are working perfectly
Can anyone please help me??

**Comment by golmschenk** [comment]
The dataset JSON files should just contain a dictionary with the keys `train`, `validation`, and `test`. The values for those keys should each be a list containing the names of the camera directories which you want to use in each case. Which cameras you want to use for each dataset is up to you.

(Note: I also replied to your email with the additional information you requested there)
